### ISSUE TITLE
无法正确操作，使用提供的test.apk也报错

### ISSUE THREAD

**Issue by prohack** [yongyecc/dexsheller#1]

**Comment by prohack** [comment]
E:\AboutAndroid\dexsheller-master>python sosheller.py -f test.apk
[*] 纭畾鍔犲瘑瑙ｅ瘑绠楁硶锛屽紓鎴? 255Traceback (most recent call last):
  File "sosheller.py", line 263, in <module>
    print("[*] 纭畾鍔犲瘑瑙ｅ瘑绠楁硶锛屽紓鎴? {}".format(str(inKey)))
IOError: [Errno 2] No such file or directory

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/118662517-43239d00-b81a-11eb-805e-744d2e5f1ede.png)
![image](https://user-images.githubusercontent.com/11989916/118662696-68b0a680-b81a-11eb-83e4-d3fe9256b5fb.png)

**Comment by Khaos116** [comment]
1.安装：
pip install Pillow
pip install filetype
2.需要使用python3.x
3.python sosheller.py -f test.apk

这样就可以运行了

**Comment by Khaos116** [comment]
1.运行成功后的APK无法安装
2.替换为自己编写的Hello Word无法编译通过
![image](https://user-images.githubusercontent.com/11989916/118671805-f93eb500-b821-11eb-828d-cd39b389a6e5.png)

**Comment by yongyecc** [comment]
> 1.运行成功后的APK无法安装
> 2.替换为自己编写的Hello Word无法编译通过
> ![image](https://user-images.githubusercontent.com/11989916/118671805-f93eb500-b821-11eb-828d-cd39b389a6e5.png)

这个报错很明显是python运行错误，你使用python跑一下这串命令看看是什么问题。
