### ISSUE TITLE
你这个在模拟器上能用，真机就闪退了

### ISSUE THREAD

**Issue by ghost** [yongyecc/dexsheller#3]

**Comment by yongyecc** [comment]
我这个暂时只提供x86架构得so库，真机需要arm架构的

**Comment by ghost** [comment]
好家伙，秒回啊，我也来研究研究一下

**Comment by ghost** [comment]
有那个编译cpp的android.mk文件吗

**Comment by yongyecc** [comment]
> 有那个编译cpp的android.mk文件吗

那个是交叉编译的，你可以自己用androidstudio创建一个native c++项目，然后把cpp文件放进去，再把cmake.txt替换一下，然后make编译就ok了

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
so问题搞定了，启动之后会找不到源app的类

**Comment by yongyecc** [comment]
> so问题搞定了，启动之后会找不到源app的类

是多个DEX文件吗，暂时还不支持多个DEX文件。

**Comment by ghost** [comment]
一个dex,我测试用得，才几M，反编译出来那个启动类还是源app的

**Comment by ghost** [comment]
看了一下，还真有多个dex,自动给我分了，不好意思，再测一下

**Comment by yongyecc** [comment]
> 看了一下，还真有多个dex,自动给我分了，不好意思，再测一下

最近也在研究多DEX加载问题，你也可以研究研究

**Comment by ghost** [comment]
可以，不错，能正常跑起来了。 👍 我才刚开始研究加壳解壳这
个，熟了再跟你探讨探讨标签😊😊

**Comment by ghost** [comment]
用了这个组件化的库好像会出问题 https://juejin.cn/post/6844903687488274445 AppJoint

**Comment by ghost** [comment]
感觉像是application启动的时候少了一下自定义的类加载进来或者一些第三方的类在application加载的

**Comment by yongyecc** [comment]
多DEX加载解决了，参考QQ空间热修复，后面我会把相关功能添加然后更新一版就可以加载多DEX了

**Comment by ghost** [comment]
牛，等你哟
